### ISSUE TITLE
Potential incompatibility with module "PopOut!"? 

### ISSUE THREAD

**Issue by coffiarts** [xaukael/inline-chats#2]
Am I getting it right that these inline macros dont' work in combination with [PopOut!](https://github.com/League-of-Foundry-Developers/fvtt-module-popout)?
At least in my setup, macro links don't do anything whenever my journal is "popped out" to a secondary window.
After "popping" the window "in", links work again.

It might be a similar issue as also detected for the similar [inline-macro-execution](https://github.com/fpiechowski/inline-macro-execution/issues/1) module, the only difference being: In this case here I get some console errors at least:
**EDIT:** This assumption wasn't correct. It has turned out (see below) that inline-chats works fine. It's that other module that's still having this issue, here everything is resolved.

![image](https://github.com/xaukael/inline-chats/assets/39616483/389c56d1-79d4-4027-82a2-5332895cc430)

![image](https://github.com/xaukael/inline-chats/assets/39616483/b67cb14e-1a63-4bab-af90-80b058f17b01)

**Comment by coffiarts** [comment]
Any news on this? Or maybe others experiencing the same?
I'd be happy if I wouldn't have to switch back to good old (but clumsy) "@Macro[]" syntax for my tons of journal links, which I have written based in inline-chats.

**Comment by xaukael** [comment]
I just tested it and it seems to work fine for me. What version of foundry are you on? Have you tried with just PopOut! and Inline Chats? What is an example of what you put in the inline chat?

**Comment by coffiarts** [comment]
Thanks for your feedback on this 👍 
Well, honestly, it's a bit embarrasing: Can't reproduce it anymore by now!
Maybe there was a mod conflict I hadn't been aware of, that has resolved itself by a recent update of another mod?

BTW, I am using inline-chats mainly for more complex macro calls rather than for "simple" chat commands.
Such as ...
[[! /macro _My macro name with even spaces in it_ param1=value param2=value]]
Even macro names with spaces in them seem to work (which I wouldn't have expected)! That's brilliant!

I am still experiencing some _sporadic_ failures of my links, though but this is _very erratic_. 
Not enough proof to keep this issue open. I will investigate further and close this for now.
Sorry for the false alarm.
